sudo: required
language: node_js
cache: npm

node_js:
  - "12"

install:
  - npm install -g truffle
  - npm install

script:
  - echo "$secret" > .secret
  - echo "$infura_key" > .infura_key
  - truffle compile
